#@data/values
---

#! e.g. "gcr.io/your-gcp-project/issues2stories:latest"
container_image:

#! e.g. "your-org" from https://github.com/your-org/your-repo
github_org:
#! e.g. "your-repo" from https://github.com/your-org/your-repo
github_repo:

#! e.g. "issues2stories.your-zone.com"
domain_name:

#! e.g. "issues2stories-external-load-balancer-ingress-ip"
ingress_global_static_ip_name:

#! Tracker API token. The user account who owns this token must
#! have at least read-only access to your Tracker project.
#! The webhook will use this token whenever it hears about
#! a changed Tracker user story to call the Tracker API to get
#! more details about the story.
#! e.g. "1c11aef11aef1f11111111111111111111111111"
tracker_token:

#! GitHub personal access token. The user account who owns this token must
#! have write access to your GitHub project, and the token must be created
#! with at least "full repo" access permission. This token will be used to
#! make API calls to read and edit GitHub issues in your GitHub project.
#! e.g. "1c11aef11aef1f11111111111111111111111111"
github_token:

#! See issues2stories project README for how to configure this.
#! The value should be formatted a string which can be evaluated as a YAML map.
#! Or the value can be omitted which will disable the feature which updates
#! the GitHub issue's assignees field when the Tracker story's owner(s) changes.
#! e.g. using a pipe to start a multiline string:
#! tracker_id_to_github_username_mapping: |
#!   {
#!     3344177: cfryanr,
#!     1234567: some-other-github-username,
#!   }
tracker_id_to_github_username_mapping:
